name: Python Bot

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Start Bot
      run: git clone https://github.com/luanwillianzh/BotMb-Telegram.git ; cd BotMb-Telegram ; pip install poetry ; python3 -m poetry install ; python3 main.py
